services:
  postgres:
    image: 'postgres:16-alpine'
    container_name: greenleaf_oasis_db
    environment:
      - 'POSTGRES_DB=greenleaf_oasis'
      - 'POSTGRES_PASSWORD=tomchak'
      - 'POSTGRES_USER=alina'
    ports:
      - '5433:5432'