spring:
  application:
    name: pet-project
    security:
      jwt:
        secret-key: 53GPIIKU5zROcVta0M8dT58BRD7i2FgnIRFFJWrNLDUwor8w8VpsHYD/HWWanH69
        expiration: 86400000
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  datasource:
    url: jdbc:postgresql://localhost:5433/greenleaf_oasis
    username: alina
    password: tomchak
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        ddl-auto: validate

