spring:
  application:
    name: pet-project
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  datasource:
    url: jdbc:postgresql://localhost:5433/greenleaf_oasis
    username: alina
    password: tomchak
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        ddl-auto: validate
